FROM golang:alpine as builder
RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN go build -o echo-server .

FROM alpine
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /build/echo-server /app/
COPY --from=builder /build/config* /app/
WORKDIR /app
CMD [ "/app/echo-server", "server", "--config", "config.local.yaml"]